# Generated by Django 4.2.7 on 2023-11-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_user_rename_cashondeliverydetails_cheackout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='login',
        ),
    ]
