# Generated by Django 4.2.7 on 2023-11-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0004_rename_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
