# Generated by Django 4.1.13 on 2023-11-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_userprofile_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cheackout',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
